# Generated by Django 5.1.6 on 2025-07-22 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_student_limit_user_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_limit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Student Limit'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('twitch', 'Twitch'), ('facebook', 'Facebook')], max_length=20)),
                ('embed_code', models.TextField()),
                ('is_live', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
