# Generated by Django 5.1.6 on 2025-08-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_alter_user_student_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
