# Generated by Django 5.1.6 on 2025-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_section',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='First Section'),
        ),
        migrations.AddField(
            model_name='user',
            name='fourth_section',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Fourth Section'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_section',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Second Section'),
        ),
        migrations.AddField(
            model_name='user',
            name='text_below',
            field=models.TextField(blank=True, null=True, verbose_name='Text Below'),
        ),
        migrations.AddField(
            model_name='user',
            name='text_in_picture',
            field=models.TextField(blank=True, null=True, verbose_name='Text In Picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='third_section',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Third Section'),
        ),
    ]
