# Generated by Django 5.1.6 on 2025-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_first_section_user_fourth_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='instgram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_background',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Social Background'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube Link'),
        ),
    ]
