# Generated by Django 5.1.6 on 2025-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_facebook_link_user_instgram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Facebook Icon'),
        ),
        migrations.AddField(
            model_name='user',
            name='instgram_icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Instagram Icon'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Youtube Icon'),
        ),
    ]
