# Generated by Django 5.1.6 on 2025-08-20 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_packagesubscribe_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_en', models.CharField(max_length=100, verbose_name='Method en')),
                ('method_ar', models.CharField(max_length=100, verbose_name='Method ar')),
                ('photo', models.ImageField(upload_to='payment_method_images/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='packagesubscribe',
            old_name='packagename',
            new_name='packagename_en',
        ),
        migrations.AddField(
            model_name='packagesubscribe',
            name='packagename_ar',
            field=models.CharField(default='s', max_length=100, verbose_name='Package Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagesubscribe',
            name='payment_method',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.paymentmethodpackage', verbose_name='Payment Method'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentMethodUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_en', models.CharField(max_length=100, verbose_name='Method en')),
                ('method_ar', models.CharField(max_length=100, verbose_name='Method ar')),
                ('photo', models.ImageField(upload_to='payment_method_images/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
