# Generated by Django 5.1.6 on 2025-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_paymentmethodpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Thumbnail'),
        ),
    ]
