# Generated by Django 5.1.6 on 2025-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscribe',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug Field'),
        ),
    ]
