# Generated by Django 5.1.6 on 2025-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_packagesubscribe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethoduser',
            name='number',
            field=models.CharField(default='s', max_length=100, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
