# Generated by Django 5.1.6 on 2025-08-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_paymentmethoduser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethoduser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method_images/', verbose_name='Photo'),
        ),
    ]
