# Generated by Django 5.1.6 on 2025-08-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_paymentmethoduser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethoduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
