# Generated by Django 5.1.6 on 2025-08-22 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_course_currency'),
        ('users', '0015_paymentmethoduser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_info', models.CharField(max_length=100, verbose_name='Account Info / account number')),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='access_course_request_images/', verbose_name='Screen Shot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_course_requests', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_course_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Access Course Request',
                'verbose_name_plural': 'Access Course Requests',
            },
        ),
    ]
