# Generated by Django 5.1.6 on 2025-08-23 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_accesscourserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscourserequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theusers', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
