# Generated by Django 5.1.6 on 2025-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_accesscourserequest_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubscribe',
            name='packagename_ar',
            field=models.CharField(max_length=100, verbose_name='Package Name AR'),
        ),
        migrations.AlterField(
            model_name='packagesubscribe',
            name='packagename_en',
            field=models.CharField(max_length=100, verbose_name='Package Name En'),
        ),
    ]
