# Generated by Django 5.1.6 on 2025-08-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_packagesubscribe_packagename_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesubscribe',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='paymentmethodpackage',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.packagesubscribe', verbose_name='Package'),
            preserve_default=False,
        ),
    ]
