# Generated by Django 5.1.6 on 2025-08-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_packagesubscribe_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentmethodpackages', to='users.packagesubscribe', verbose_name='Package'),
        ),
    ]
