# Generated by Django 5.1.6 on 2025-08-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_paymentmethodpackage_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodpackage',
            name='number',
            field=models.CharField(default='s', max_length=100, verbose_name='Number / account info '),
            preserve_default=False,
        ),
    ]
