# Generated by Django 5.1.6 on 2025-08-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_paymentmethodpackage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscribe',
            name='description_ar',
            field=models.TextField(default='2', verbose_name='Package Description AR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagesubscribe',
            name='description_en',
            field=models.TextField(default='asd', verbose_name='Package Description EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagesubscribe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/', verbose_name='Package Thumbnail'),
        ),
    ]
