# Generated by Django 5.1.6 on 2025-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_packagesubscribe_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscribe',
            name='currency',
            field=models.CharField(default='EGP', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='packagesubscribe',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
