# Generated by Django 5.1.6 on 2025-08-23 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_packagesubscribe_currency_packagesubscribe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_info', models.CharField(max_length=100, verbose_name='Account Info / account number')),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='access_course_request_images/', verbose_name='Screen Shot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesss_packages_request', to='users.packagesubscribe', verbose_name='Package')),
                ('teacher', models.ManyToManyField(blank=True, null=True, related_name='requestedpackagesaccess', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagesrequest', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Access Package Request',
                'verbose_name_plural': 'Access Package Requests',
            },
        ),
    ]
