# Generated by Django 5.1.6 on 2025-08-24 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_accesspackagerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_main_page',
            field=models.BooleanField(default=True, verbose_name='In Main Page'),
        ),
        migrations.AlterField(
            model_name='accesspackagerequest',
            name='teacher',
            field=models.ManyToManyField(related_name='requestedpackagesaccess', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
