# Generated by Django 5.1.6 on 2025-08-24 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_in_main_page_alter_accesspackagerequest_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whychoose_en', models.TextField(max_length=1000, verbose_name='Why choose this teacher en')),
                ('whychoose_ar', models.TextField(max_length=1000, verbose_name='Why choose this teacher ar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whychooseuser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
