# Generated by Django 5.1.6 on 2025-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_whychooseuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whychooseuser',
            options={'verbose_name': 'Why Choose User', 'verbose_name_plural': 'Why Choose Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name AR'),
        ),
    ]
