# Generated by Django 5.1.6 on 2025-07-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_thumbnail_course_thumbnail_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Course Thumbnail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail_pc',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Course Thumbnail'),
        ),
    ]
