# Generated by Django 5.1.6 on 2025-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_thumbnail_mobile_alter_course_thumbnail_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
