# Generated by Django 5.1.6 on 2025-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courselevel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_level_images/', verbose_name='Course Level Thumbnail'),
        ),
    ]
