# Generated by Django 5.1.6 on 2025-07-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courselevel_slug_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselevel',
            name='slug_field',
        ),
    ]
