# Generated by Django 5.1.6 on 2025-07-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_courselevel_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='slug_field',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug Field'),
        ),
    ]
