# Generated by Django 5.1.6 on 2025-07-26 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_courselevel_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='course.course', verbose_name='Course'),
        ),
    ]
