# Generated by Django 5.1.6 on 2025-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_courselevel_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselevel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetype',
            name='course',
        ),
        migrations.AddField(
            model_name='courselevel',
            name='course',
            field=models.ManyToManyField(to='course.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='course',
            field=models.ManyToManyField(to='course.course', verbose_name='Course'),
        ),
    ]
