# Generated by Django 5.1.6 on 2025-08-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_aboutthecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutthecourse',
            name='owner',
        ),
    ]
