# Generated by Django 5.1.6 on 2025-08-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_aboutthecourse_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutthecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_the_courses', to='course.course', verbose_name='Course'),
        ),
    ]
