# Generated by Django 5.1.6 on 2025-08-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_course_info_background_subscripedcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='owner',
        ),
    ]
