# Generated by Django 5.1.6 on 2025-08-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_episode_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='students',
        ),
    ]
