# Generated by Django 5.1.6 on 2025-08-14 11:48

import course.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_episode_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='end_date',
            field=models.DateField(default=course.models.default_end_date, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
