# Generated by Django 5.1.6 on 2025-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_episode_duration_hours_alter_episode_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration_hours',
            field=models.FloatField(blank=True, default=0, help_text='By hours', null=True, verbose_name='Duration Hours'),
        ),
    ]
