# Generated by Django 5.1.6 on 2025-08-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_episode_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_background',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title In'),
        ),
    ]
