# Generated by Django 5.1.6 on 2025-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_title_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title_background',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Course title in'),
        ),
    ]
