# Generated by Django 5.1.6 on 2025-08-16 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_episode_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title ar')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title en')),
                ('question_1_ar', models.TextField(verbose_name='Question 1 ar')),
                ('question_1_en', models.TextField(verbose_name='Question 1 en')),
                ('question_2_ar', models.TextField(verbose_name='Question 2 ar')),
                ('question_2_en', models.TextField(verbose_name='Question 2 en')),
                ('question_3_ar', models.TextField(verbose_name='Question 3 ar')),
                ('question_3_en', models.TextField(verbose_name='Question 3 en')),
                ('question_4_ar', models.TextField(verbose_name='Question 4 ar')),
                ('question_4_en', models.TextField(verbose_name='Question 4 en')),
                ('answer', models.CharField(choices=[('1', 'First Choice'), ('2', 'Second Choice'), ('3', 'Third Choice'), ('4', 'Fourth Choice')], max_length=200, verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.episode', verbose_name='Episode')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('total', models.IntegerField(default=0, verbose_name='Total Questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='course.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title ar')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title en')),
                ('file', models.FileField(upload_to='summaries/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='course.episode', verbose_name='Episode')),
            ],
        ),
    ]
