# Generated by Django 5.1.6 on 2025-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_quizquestion_quizresult_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name': 'Quiz Result', 'verbose_name_plural': 'Quiz Results'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterModelOptions(
            name='watchedepisods',
            options={'verbose_name': 'Watched Episode', 'verbose_name_plural': 'Watched Episodes'},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='answers',
            field=models.TextField(default='s', editable=False, verbose_name='Answers'),
            preserve_default=False,
        ),
    ]
