# Generated by Django 5.1.6 on 2025-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_quizquestion_options_alter_quizresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='answers',
            field=models.TextField(verbose_name='Answers'),
        ),
    ]
