# Generated by Django 5.1.6 on 2025-08-21 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_alter_quizresult_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutthecourse',
            name='course',
        ),
        migrations.AddField(
            model_name='aboutthecourse',
            name='level',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='about_the_courses', to='course.courselevel', verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselevel',
            name='description_ar',
            field=models.TextField(default=' سوي سيسي يسي يسي يس شيشسي فقغ بلا ضث ضصث يسش', verbose_name='Course Level Description ar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselevel',
            name='description_en',
            field=models.TextField(default=' Hey you this is a smmury of the thing here ', verbose_name='Course Level Description en'),
            preserve_default=False,
        ),
    ]
