# Generated by Django 5.1.6 on 2025-08-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_remove_aboutthecourse_course_aboutthecourse_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost'),
        ),
    ]
