# Generated by Django 5.1.6 on 2025-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_course_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='EGP', max_length=10, verbose_name='Currency'),
        ),
    ]
