# Generated by Django 5.1.6 on 2025-08-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0032_alter_course_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=100, verbose_name='Key')),
                ('Value', models.CharField(max_length=100, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='GloblaChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prompt', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Global Chat Bot',
                'verbose_name_plural': 'Global Chat Bots',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='ChatBotForEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prompt', models.TextField(max_length=1000)),
                ('pdf', models.FileField(upload_to='pdf/', verbose_name='PDF File')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='course.episode', verbose_name='Episode')),
            ],
            options={
                'verbose_name': 'Chat Bot For Episodes',
                'verbose_name_plural': 'Chat Bots For Episodes',
            },
        ),
    ]
