# Generated by Django 5.1.6 on 2025-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvars',
            name='Value',
            field=models.TextField(max_length=100, verbose_name='Value'),
        ),
    ]
