# Generated by Django 5.1.6 on 2025-08-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_globalvars_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotforep',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='chatbotforep',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='PDF File'),
        ),
    ]
